package com.jdcy.model.entity.persist;
// Generated 2017-7-15 14:18:28 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Departments generated by hbm2java
 */
public class Departments implements java.io.Serializable {

	private Integer did;
	private String dname;
	private Set employesses = new HashSet(0);

	public Departments() {
	}

	public Departments(String dname) {
		this.dname = dname;
	}

	public Departments(String dname, Set employesses) {
		this.dname = dname;
		this.employesses = employesses;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public Set getEmployesses() {
		return this.employesses;
	}

	public void setEmployesses(Set employesses) {
		this.employesses = employesses;
	}

}
