package com.jdcy.model.entity.persist;
// Generated 2017-7-15 14:18:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Employess generated by hbm2java
 */
public class Employess implements java.io.Serializable {

	private Integer eid;
	private Departments departments;
	private String ename;
	private Character esex;
	private Date ebirthday;

	public Employess() {
	}

	public Employess(String ename) {
		this.ename = ename;
	}

	public Employess(Departments departments, String ename, Character esex, Date ebirthday) {
		this.departments = departments;
		this.ename = ename;
		this.esex = esex;
		this.ebirthday = ebirthday;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Departments getDepartments() {
		return this.departments;
	}

	public void setDepartments(Departments departments) {
		this.departments = departments;
	}

	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public Character getEsex() {
		return this.esex;
	}

	public void setEsex(Character esex) {
		this.esex = esex;
	}

	public Date getEbirthday() {
		return this.ebirthday;
	}

	public void setEbirthday(Date ebirthday) {
		this.ebirthday = ebirthday;
	}

}
